#!/usr/bin/env bash
# Deploy Local Telegram Bot API to Fly.io (always-on HTTPS → TELEGRAM_BOT_API_URL).
# Requires: flyctl auth login (or FLY_API_TOKEN), TELEGRAM_API_ID + TELEGRAM_API_HASH.
#
# Usage (from repo root):
#   npm run telegram:bot-api:fly
#   # or: ./deploy/telegram-bot-api/deploy-fly.sh

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

export PATH="${HOME}/.fly/bin:/usr/local/bin:/opt/homebrew/bin:$PATH"
FLY="$(command -v flyctl || command -v fly || true)"
if [[ -z "$FLY" ]]; then
  echo "flyctl not found. Install: curl -L https://fly.io/install.sh | sh" >&2
  echo "Then: fly auth login" >&2
  exit 1
fi

if ! "$FLY" auth whoami >/dev/null 2>&1; then
  echo "Not logged in to Fly. Run: fly auth login" >&2
  echo "Or export FLY_API_TOKEN=…" >&2
  echo ""
  echo "Until then, Mac hop durability: npm run mac-hop:install" >&2
  exit 1
fi

load_dotenv() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  set -a
  # shellcheck disable=SC1090
  source <(grep -E '^(TELEGRAM_API_ID|TELEGRAM_API_HASH)=' "$f" | sed 's/\r$//' || true)
  set +a
}

load_dotenv "$ROOT/.env.local"
load_dotenv "$ROOT/.env"
load_dotenv "$DIR/.env"

if [[ -z "${TELEGRAM_API_ID:-}" || -z "${TELEGRAM_API_HASH:-}" ]]; then
  echo "Set TELEGRAM_API_ID and TELEGRAM_API_HASH (my.telegram.org)" >&2
  exit 1
fi

APP_NAME="${FLY_BOTAPI_APP:-arabicbuzz-telegram-bot-api}"
REGION="${FLY_REGION:-fra}"

cat >fly.toml <<EOF
# Generated by deploy-fly.sh — no secrets in this file
app = '${APP_NAME}'
primary_region = '${REGION}'

[build]
  dockerfile = 'Dockerfile'

[env]
  TELEGRAM_LOCAL = '1'

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
EOF

"$FLY" apps create "${APP_NAME}" --org "${FLY_ORG:-personal}" 2>/dev/null || true

"$FLY" secrets set \
  TELEGRAM_API_ID="${TELEGRAM_API_ID}" \
  TELEGRAM_API_HASH="${TELEGRAM_API_HASH}" \
  --app "${APP_NAME}"

"$FLY" deploy --app "${APP_NAME}" --remote-only --strategy rolling

URL="https://${APP_NAME}.fly.dev"
echo ""
echo "✅ Deployed Local Bot API"
echo "  Smoke: curl -sS '${URL}/bot\$TELEGRAM_BOT_TOKEN/getMe'"
echo "  CranL: ./scripts/cranl-put-env-keys.sh --restart TELEGRAM_BOT_API_URL=${URL}"
echo "TELEGRAM_BOT_API_URL=${URL}"

if [[ -x "$ROOT/scripts/cranl-put-env-keys.sh" ]]; then
  bash "$ROOT/scripts/cranl-put-env-keys.sh" --restart "TELEGRAM_BOT_API_URL=${URL}" || true
fi
