#!/usr/bin/env bash
# Deploy MCP Toolbox to Fly.io and print the MCP_TOOLBOX_URL to set on Netlify.
# Requires: flyctl auth, Docker (or Fly remote builder), and deploy/toolbox/.env
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if ! command -v flyctl >/dev/null 2>&1 && ! command -v fly >/dev/null 2>&1; then
  echo "flyctl not found. Install: https://fly.io/docs/hands-on/install-flyctl/" >&2
  echo "  curl -L https://fly.io/install.sh | sh" >&2
  exit 1
fi
FLY="$(command -v flyctl || command -v fly)"

if [[ ! -f .env ]]; then
  echo "Missing .env — run: ./scripts/env-from-database-url.sh" >&2
  exit 1
fi

APP_NAME="${FLY_APP_NAME:-arabicbuzz-mcp-toolbox}"

if [[ ! -f fly.toml ]]; then
  cat > fly.toml <<EOF
# Generated by scripts/deploy-fly.sh — adjust region as needed.
app = "${APP_NAME}"
primary_region = "${FLY_REGION:-iad}"

[build]
  image = "us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:1.8.0"

[env]
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
EOF
  echo "Wrote fly.toml for app=${APP_NAME}"
fi

# Create app if needed (ignore "already exists")
"$FLY" apps create "${APP_NAME}" --org "${FLY_ORG:-personal}" 2>/dev/null || true

# Import Postgres secrets from .env (never print values)
set -a
# shellcheck disable=SC1091
source .env
set +a
"$FLY" secrets set \
  POSTGRES_HOST="${POSTGRES_HOST}" \
  POSTGRES_PORT="${POSTGRES_PORT:-5432}" \
  POSTGRES_DATABASE="${POSTGRES_DATABASE}" \
  POSTGRES_USER="${POSTGRES_USER}" \
  POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
  POSTGRES_QUERY_PARAMS="${POSTGRES_QUERY_PARAMS:-sslmode=require}" \
  --app "${APP_NAME}"

"$FLY" deploy --app "${APP_NAME}" --remote-only \
  --strategy rolling

URL="https://${APP_NAME}.fly.dev/mcp"
echo
echo "Deployed. Set on Netlify (then redeploy):"
echo "  npx netlify-cli env:set MCP_TOOLBOX_URL '${URL}' --force --context production --context deploy-preview --context branch-deploy"
echo "MCP_TOOLBOX_URL=${URL}"
